# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"
command:
  build:
    - "composer update"
  init:
  test:
  run:
  dev:
    - "echo 'I am executed in dev mode'"
